/*INSERTS TABELA FUNCAO*/
INSERT INTO FUNCAO(DESCRICAO) VALUES ('GERENTE DE VENDAS');
INSERT INTO FUNCAO(DESCRICAO) VALUES ('ANALISTA DE RECURSOS HUMANOS');
INSERT INTO FUNCAO(DESCRICAO) VALUES ('ASSISTENTE FINANCEIRO');
INSERT INTO FUNCAO(DESCRICAO) VALUES ('DESENVOLVEDOR DE SOFTWARE');
INSERT INTO FUNCAO(DESCRICAO) VALUES ('ANALISTA DE QUALIDADE');
INSERT INTO FUNCAO(DESCRICAO) VALUES ('COORDENADOR DE LOGÍSTICA');
INSERT INTO FUNCAO(DESCRICAO) VALUES ('ESPECIALISTA DE MARKETING');
INSERT INTO FUNCAO(DESCRICAO) VALUES ('TÉCNICO DE SUPORTE');
INSERT INTO FUNCAO(DESCRICAO) VALUES ('COORDENADOR DE PROJETOS');
INSERT INTO FUNCAO(DESCRICAO) VALUES ('ANALISTA DE COMPRAS');
SELECT * FROM FUNCAO;

/*INSERTS TABELA USUARIO */
INSERT INTO USUARIOS(NOME, SOBRENOME, CPF, EMAIL, SENHA, FUNCAO_ID, ATIVO)
VALUES ('JOÃO', 'SILVA', '111.111.111-11', 'JOAO.SILVA@EXAMPLE.COM', 'SENHA123', 1, 0);
INSERT INTO USUARIOS(NOME, SOBRENOME, CPF, EMAIL, SENHA, FUNCAO_ID, ATIVO)
VALUES ('MARIA', 'SOUZA', '222.222.222-22', 'MARIA.SOUZA@EXAMPLE.COM', 'SENHA456', 2, 0);
INSERT INTO USUARIOS(NOME, SOBRENOME, CPF, EMAIL, SENHA, FUNCAO_ID, ATIVO)
VALUES ('PEDRO', 'SANTOS', '333.333.333-33', 'PEDRO.SANTOS@EXAMPLE.COM', 'SENHA789', 3, 0);
INSERT INTO USUARIOS(NOME, SOBRENOME, CPF, EMAIL, SENHA, FUNCAO_ID, ATIVO)
VALUES ('ANA', 'RIBEIRO', '444.444.444-44', 'ANA.RIBEIRO@EXAMPLE.COM', 'SENHA321', 4, 0);
INSERT INTO USUARIOS(NOME, SOBRENOME, CPF, EMAIL, SENHA, FUNCAO_ID, ATIVO)
VALUES ('CARLOS', 'FERREIRA', '555.555.555-55', 'CARLOS.FERREIRA@EXAMPLE.COM', 'SENHA654', 5, 0);
INSERT INTO USUARIOS(NOME, SOBRENOME, CPF, EMAIL, SENHA, FUNCAO_ID, ATIVO)
VALUES ('SANDRA', 'GOMES', '666.666.666-66', 'SANDRA.GOMES@EXAMPLE.COM', 'SENHA987', 6, 0);
INSERT INTO USUARIOS(NOME, SOBRENOME, CPF, EMAIL, SENHA, FUNCAO_ID, ATIVO)
VALUES ('RAFAEL', 'PEREIRA', '777.777.777-77', 'RAFAEL.PEREIRA@EXAMPLE.COM', 'SENHA123', 7, 0);
INSERT INTO USUARIOS(NOME, SOBRENOME, CPF, EMAIL, SENHA, FUNCAO_ID, ATIVO)
VALUES ('FERNANDA', 'ALMEIDA', '888.888.888-88', 'FERNANDA.ALMEIDA@EXAMPLE.COM', 'SENHA456', 8, 0);
INSERT INTO USUARIOS(NOME, SOBRENOME, CPF, EMAIL, SENHA, FUNCAO_ID, ATIVO)
VALUES ('LUCAS', 'MENDES', '999.999.999-99', 'LUCAS.MENDES@EXAMPLE.COM', 'SENHA789', 9, 0);
INSERT INTO USUARIOS(NOME, SOBRENOME, CPF, EMAIL, SENHA, FUNCAO_ID, ATIVO)
VALUES ('JULIA', 'LIMA', '000.000.000-00', 'JULIA.LIMA@EXAMPLE.COM', 'SENHA321', 10, 0);
SELECT * FROM USUARIOS;
