/*CRIAÇÃO DA BANCO DE DADOS  */
CREATE DATABASE SAGAVALUE;

/*SELECIONANDO O BANCO */
USE SAGAVALUE;

/*CRIANDO TABELA DE FUNÇÃO */
CREATE TABLE FUNCAO(
ID_FUNCAO INTEGER NOT NULL AUTO_INCREMENT,
DESCRICAO VARCHAR(100) NOT NULL,
PRIMARY KEY(ID_FUNCAO));

/*CRIANDO TABELA DE USUARIO */
CREATE TABLE USUARIOS(
ID_USUARIO INTEGER NOT NULL AUTO_INCREMENT,
NOME VARCHAR(100) NOT NULL,
SOBRENOME VARCHAR(100) NOT NULL,
CPF VARCHAR(100) NOT NULL UNIQUE,
EMAIL VARCHAR(100) NOT NULL UNIQUE,
SENHA VARCHAR(100) NOT NULL,
FUNCAO_ID INTEGER NOT NULL,
ATIVO INTEGER NOT NULL,
PRIMARY KEY(ID_USUARIO),
CONSTRAINT FK_USUARIO_FUNCAO FOREIGN KEY(FUNCAO_ID) REFERENCES  FUNCAO(ID_FUNCAO));

/*CRIANDO A TABELA DE FORNECEDORES*/
CREATE TABLE FORNECEDORES(
ID_FORNECEDOR INTEGER NOT NULL AUTO_INCREMENT,
RAZAO_SOCIAL VARCHAR(100) NOT NULL,
FANTASIA VARCHAR(100),
CNPJ VARCHAR(100) NOT NULL UNIQUE,
IE INTEGER NOT NULL,
ENDERECO VARCHAR(100) NOT NULL,
TELEFONE VARCHAR(100) NOT NULL,
ATIVO INTEGER NOT NULL,
PRIMARY KEY(ID_FORNECEDOR));

/*CRIANDO A TABLE DE PRODUTOS*/
CREATE TABLE PRODUTOS(
ID_PRODUTO INTEGER NOT NULL AUTO_INCREMENT,
NOME  VARCHAR(100) NOT NULL,
NCM INTEGER NOT NULL,
GTIN INTEGER NOT NULL,
VALOR_CUSTO DOUBLE NOT NULL,
VALOR_VENDAR DOUBLE NOT NULL,
ESTOQUE INTEGER NOT NULL,
PRIMARY KEY(ID_PRODUTO));
/*ALTERAÇÃO PARA ATENDER QUANTIDADE DE CARACTERES*/
ALTER TABLE PRODUTOS MODIFY GTIN BIGINT;