/*INSERTS TABELA FUNCAO*/
INSERT INTO FUNCAO(DESCRICAO) VALUES ('GERENTE DE VENDAS');
INSERT INTO FUNCAO(DESCRICAO) VALUES ('ANALISTA DE RECURSOS HUMANOS');
INSERT INTO FUNCAO(DESCRICAO) VALUES ('ASSISTENTE FINANCEIRO');
INSERT INTO FUNCAO(DESCRICAO) VALUES ('DESENVOLVEDOR DE SOFTWARE');
INSERT INTO FUNCAO(DESCRICAO) VALUES ('ANALISTA DE QUALIDADE');
INSERT INTO FUNCAO(DESCRICAO) VALUES ('COORDENADOR DE LOGÍSTICA');
INSERT INTO FUNCAO(DESCRICAO) VALUES ('ESPECIALISTA DE MARKETING');
INSERT INTO FUNCAO(DESCRICAO) VALUES ('TÉCNICO DE SUPORTE');
INSERT INTO FUNCAO(DESCRICAO) VALUES ('COORDENADOR DE PROJETOS');
INSERT INTO FUNCAO(DESCRICAO) VALUES ('ANALISTA DE COMPRAS');
SELECT * FROM FUNCAO;

