/*CRIAÇÃO DA BANCO DE DADOS  */
CREATE DATABASE SAGAVALUE;

/*SELECIONANDO O BANCO */
USE SAGAVALUE;

/*CRIANDO TABELA DE FUNÇÃO */
CREATE TABLE FUNCAO(
ID_FUNCAO INTEGER NOT NULL,
DESCRICAO VARCHAR(100) NOT NULL,
PRIMARY KEY(ID_FUNCAO));


/*CRIANDO TABELA DE USUARIO */
CREATE TABLE USUARIOS(
ID_USUARIO INTEGER NOT NULL,
NOME VARCHAR(100) NOT NULL,
SOBRENOME VARCHAR(100) NOT NULL,
CPF VARCHAR(100) NOT NULL UNIQUE,
EMAIL VARCHAR(100) NOT NULL UNIQUE,
SENHA VARCHAR(100) NOT NULL,
FUNCAO_ID INTEGER NOT NULL,
ATIVO INTEGER NOT NULL,
PRIMARY KEY(ID_USUARIO),
CONSTRAINT FK_USUARIO_FUNCAO FOREIGN KEY(FUNCAO_ID) REFERENCES  FUNCAO(ID_FUNCAO));